### PR TITLE
25 add a rating system to the reviews

### PR DESCRIPTION
**Pull request by dbatoon**
This PR:

* Implements rating system where the users can give a rating (out of 5) for a course.
* Displays the average rating and total number of reviews of a course.

### CODE REVIEW

**Comment by dbatoon** [comment]
The view when an authenticated user goes to a course's review page:
image
image

**Comment by dbatoon** [comment]
The view when an unauthenticated user goes to a course's review page:
image
image

**Review by Naomi-Parte — APPROVED** [review]
Looking good!

**Review by richards-sam — APPROVED** [review]
looks good

**Review by dbatoon — COMMENTED** [review]
Redirection is working as intended now

**Review by Naomi-Parte — APPROVED** [review]
Re-direction after post is working now

**Pull request merged**
